Add the option of Google two factor auth to the admin
silverorange/admin pull request #95
Opened 2022-10-06 12:42 UTC by nburka

2022-10-06 17:59 UTC, nburka commented on Admin/components/AdminSite/Profile.php
> +				$img_tag->src = 'https://chart.googleapis.com/chart'.
this is unfortunately deprecated. I think we'll need to replace with Bacon https://github.com/antonioribeiro/google2fa#baconqrcode

2022-10-07 20:02 UTC, nburka commented
https://app.shortcut.com/silverorangeinc/story/37216/improve-login-for-emrap-admin

2022-10-11 13:26 UTC, nburka commented on Admin/components/AdminSite/Google2fa.php
> +		parent::initInternal();
add a check to make sure 2FA is enabled…

2022-10-11 13:30 UTC, nburka commented on Admin/components/AdminSite/Profile.php
> +				// $img_tag->src = 'https://chart.googleapis.com/chart'.
remove this

2022-10-19 19:51 UTC, gauthierm requested changes

2022-10-19 19:51 UTC, gauthierm commented on Admin/components/AdminSite/Profile.php
> +					400
Extract 400 to a class constant. I assume this is image width.

2022-10-19 19:51 UTC, gauthierm commented on Admin/components/AdminSite/Profile.php
> +				$p_tag->class = 'two-factor-secret';
prefix css class with `admin-`

2022-10-19 19:51 UTC, gauthierm commented on Admin/components/AdminSite/TwoFactorAuthentication.php
> +		$token = preg_replace(
this logic is copied in the profile page. It makes sense to move it to a separate class used in both places that wraps around `TwoFactorAuth`

2022-10-19 19:51 UTC, gauthierm commented on Admin/components/AdminSite/profile.xml
> +				<property name="title" translatable="yes">Two Factor Authentication</property>
This looks done below 👍

2022-10-19 19:51 UTC, gauthierm commented on Admin/components/AdminSite/Profile.php
> +			$this->app->session->user->two_fa_secret,
The profile page uses `$this->data_object` to refer to the account in most places. Does it make sense here too?

2022-10-20 20:44 UTC, gauthierm approved these changes

2022-10-20 20:44 UTC, merged